### ISSUE TITLE
New signing CA used by ARRL

### ISSUE THREAD

**Issue by bwarden** [hessu/aprsc#30]
Having requested a new LOTW certificate from ARRL after changing my callsign, I've discovered that they've apparently changed their signing certificate. As a result, APRS2 servers reject my certificate as having a self-signed cert in the chain. For reference, I've attached ARRL's new certificates.
[LogbookoftheWorldProductionCA.txt](https://github.com/hessu/aprsc/files/264188/LogbookoftheWorldProductionCA.txt)

**Comment by hessu** [comment]
Thanks. This is not a bug or issue with aprsc, certificates are not shipped in aprsc, so I'll close this ticket.
