### ISSUE TITLE
If one of the aprs servers is down, how the aprs network continue to run ?

### ISSUE THREAD

**Issue by pyrog** [hessu/aprsc#36]
Several aprs server are connected themselves. (Seem to be the uplink connections ?)

What happen in the following case:

1. An aprs client is connected to i.e aprs server 1
1. The network connection is lost with this specific server

Does the client "know" the other aprs servers ?
Does it could reconnect automatically itself with one of these server ?

**Comment by hessu** [comment]
APRS-IS clients typically connect to a DNS round-robin hostname with load balancing, such as rotate.aprs2.net, which returns IP addresses for multiple servers. The client can reconnect automatically to the other servers.

This is not a bug or feature request for aprsc, so marking INVALID. Please post follow-up questions to one of the relevant mailing lists (APRSSIG, aprsc group, aprs2net group).
