### ISSUE TITLE
Cygwin Version 4.4.12(3)-release (i686-pc-cygwin) not working

### ISSUE THREAD

**Issue by tsk7mde** [hessu/aprsc#46]
Hello,

when I use the application compiler I get the following error:

accept.c: In Funktion »accept_liveupgrade_single«:
accept.c:1160:40: Warnung: Zeigerziele bei Übergabe des Arguments 3 von »getpeername« unterscheiden sich im Vorzeichenbesitz [-Wpointer-sign]
  if (getpeername(fd->valueint, &sa.sa, &addr_len) != 0) {
                                        ^
In file included from accept.c:24:0:
/usr/include/sys/socket.h:26:7: Anmerkung: »socklen_t * {aka int *}« erwartet, aber Argument hat Typ »unsigned int *«
   int getpeername (int, struct sockaddr *__peer, socklen_t *);

---------------------

The start of the application is also not possible:

$ ./aprsc.exe
2017/12/03 16:49:09.033399 aprsc[12800:20000008] WARNING: Configuration: setrlimit(RLIMIT_NOFILE) failed: Too many open files
2017/12/03 16:49:09.033498 aprsc[12800:20000008] WARNING: Configuration could not raise FileLimit (not running as root), it is now 3200
Segmentation fault (Speicherabzug geschrieben)

----------------------

Cygwin Output (GNU bash, Version 4.4.12(3)-release (i686-pc-cygwin)):

thomas.schaefer@RAMPAGE-IV-E /usr/src/aprsc-master/src
$ ./configure
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc needs -traditional... no
checking for GNU make... make
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking event2/event.h usability... yes
checking event2/event.h presence... yes
checking for event2/event.h... yes
checking event2/http.h usability... yes
checking event2/http.h presence... yes
checking for event2/http.h... yes
checking event2/buffer.h usability... yes
checking event2/buffer.h presence... yes
checking for event2/buffer.h... yes
checking for event_base_new in -levent... yes
checking sys/capability.h usability... no
checking sys/capability.h presence... no
checking for sys/capability.h... no
checking sys/prctl.h usability... no
checking sys/prctl.h presence... no
checking for sys/prctl.h... no
checking for cap_init in -lcap... no
checking sys/eventfd.h usability... no
checking sys/eventfd.h presence... no
checking for sys/eventfd.h... no
checking alloca.h usability... yes
checking alloca.h presence... yes
checking for alloca.h... yes
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking sys/epoll.h usability... no
checking sys/epoll.h presence... no
checking for sys/epoll.h... no
checking netinet/sctp.h usability... no
checking netinet/sctp.h presence... no
checking for netinet/sctp.h... no
checking for atan2f... yes
checking for pthread_exit in -lpthread... yes
checking for getnameinfo... yes
checking for connect... yes
checking for gethostbyname... yes
checking for socket... yes
checking for socketpair... yes
checking for getnameinfo... (cached) yes
checking for gai_strerror... yes
checking for inet_ntop... yes
checking for inet_pton... yes
checking for __sync_fetch_and_add... yes
checking for library containing clock_gettime... none required
checking for setenv... yes
checking for putenv... yes
checking for library containing deflate... -lz
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating ac-hdrs.h
config.status: ac-hdrs.h is unchanged

thomas.schaefer@RAMPAGE-IV-E /usr/src/aprsc-master/src
$ make
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c aprsc.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c accept.c
accept.c: In Funktion »accept_liveupgrade_single«:
accept.c:1160:40: Warnung: Zeigerziele bei Übergabe des Arguments 3 von »getpeername« unterscheiden sich im Vorzeichenbesitz [-Wpointer-sign]
  if (getpeername(fd->valueint, &sa.sa, &addr_len) != 0) {
                                        ^
In file included from accept.c:24:0:
/usr/include/sys/socket.h:26:7: Anmerkung: »socklen_t * {aka int *}« erwartet, aber Argument hat Typ »unsigned int *«
   int getpeername (int, struct sockaddr *__peer, socklen_t *);
       ^~~~~~~~~~~
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c worker.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c errno_aprsc.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c login.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c incoming.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c dupecheck.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c outgoing.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c clientlist.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c client_heard.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c parse_aprs.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c parse_qc.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c messaging.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c config.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c netlib.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c xpoll.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c acl.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c cfgfile.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c passcode.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c uplink.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c rwlock.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c hmalloc.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c hlog.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c keyhash.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c filter.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c cellmalloc.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c historydb.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c counterdata.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c status.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c cJSON.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c http.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c ssl.c
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c sctp.c
Generating version_data.h
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c version.c
gcc  -g -o aprsc aprsc.o accept.o worker.o errno_aprsc.o login.o incoming.o dupecheck.o outgoing.o clientlist.o client_heard.o parse_aprs.o parse_qc.o messaging.o config.o netlib.o xpoll.o acl.o cfgfile.o passcode.o uplink.o rwlock.o hmalloc.o hlog.o keyhash.o filter.o cellmalloc.o historydb.o counterdata.o status.o cJSON.o http.o ssl.o sctp.o version.o  -levent   -lpthread    -lz
perl -ne "s{\@DATEVERSION\@}{2.1.4- - 2017 Dezember 03}g;       \
          s{\@VARRUN\@}{/opt/aprsc/logs}g;                      \
          s{\@VARLOG\@}{/opt/aprsc/logs}g;                      \
          s{\@CFGFILE\@}{/opt/aprsc/etc/aprsc.conf}g;                   \
          print;"                                       \
 < aprsc.8.in > aprsc.8

thomas.schaefer@RAMPAGE-IV-E /usr/src/aprsc-master/src
$ make install
Generating version_data.h
gcc -g -O2  -march=i686  -Wall -Wstrict-prototypes -D_REENTRANT -c version.c
gcc  -g -o aprsc aprsc.o accept.o worker.o errno_aprsc.o login.o incoming.o dupecheck.o outgoing.o clientlist.o client_heard.o parse_aprs.o parse_qc.o messaging.o config.o netlib.o xpoll.o acl.o cfgfile.o passcode.o uplink.o rwlock.o hmalloc.o hlog.o keyhash.o filter.o cellmalloc.o historydb.o counterdata.o status.o cJSON.o http.o ssl.o sctp.o version.o  -levent   -lpthread    -lz
./install-sh  -m 755 -d /opt/aprsc/etc
./install-sh  -m 755 -d /opt/aprsc/logs
./install-sh  -m 755 -d /opt/aprsc/data
./install-sh  -m 755 -d /opt/aprsc/web
./install-sh  -m 755 aprsc /opt/aprsc/sbin/aprsc
./install-sh  -m 755 aprsc_munin /opt/aprsc/sbin/aprsc_munin
./install-sh  -m 644 aprsc.8 /man/man8/aprsc.8
./install-sh  -m 644 web/aprsc.css web/aprsc.js web/aprsc-graph.js web/strings-en.json web/strings-fi.json web/index.html web/favicon.ico web/aprsc-logo4.png web/aprsc-logo4@2x.png web/aprsc-joulukissa.jpg web/excanvas.min.js web/angular.min.js web/angular-translate.min.js web/angular-translate-loader-url.min.js web/ngDialog.min.js web/ngDialog.min.css web/ngDialog-theme-plain.min.css web/jquery.min.js web/jquery.flot.min.js web/jquery.flot.time.min.js web/jquery.flot.selection.min.js web/jquery.flot.resize.min.js web/bootstrap/css/bootstrap.min.css web/bootstrap/fonts/glyphicons-halflings-regular.eot web/bootstrap/fonts/glyphicons-halflings-regular.ttf web/bootstrap/fonts/glyphicons-halflings-regular.woff web/bootstrap/fonts/glyphicons-halflings-regular.woff2 /opt/aprsc/web
if [ ! -f  /opt/aprsc/etc/aprsc.conf ] ; then \
        ./install-sh  -m 644 aprsc.conf /opt/aprsc/etc/aprsc.conf ; \
else true ; fi

thomas.schaefer@RAMPAGE-IV-E /usr/src/aprsc-master/src
$ cd /opt/aprsc/

thomas.schaefer@RAMPAGE-IV-E /opt/aprsc
$ cd sbin

thomas.schaefer@RAMPAGE-IV-E /opt/aprsc/sbin
$ ./aprsc.exe
2017/12/03 16:49:09.033399 aprsc[12800:20000008] WARNING: Configuration: setrlimit(RLIMIT_NOFILE) failed: Too many open files
2017/12/03 16:49:09.033498 aprsc[12800:20000008] WARNING: Configuration could not raise FileLimit (not running as root), it is now 3200
Segmentation fault (Speicherabzug geschrieben)

thomas.schaefer@RAMPAGE-IV-E /opt/aprsc/sbin
$

**Comment by tsk7mde** [comment]
[Cygwin_Out.zip](https://github.com/hessu/aprsc/files/1524977/Cygwin_Out.zip)

**Comment by hessu** [comment]
Here are some hints for starting the debugging:

- The warning given by the compiler (accept.c) might be unrelated to the crash; it's just a warning. I'm not sure what it's saying, since it's in German; please run with English localisation (LANG=C) if you wish me to decipher the output.
- The paste above does not indicate if you edited etc/aprsc.conf to suit your configuration. You'll need to edit it for things to work.
- There might be something useful in logs/aprsc.log too.
- I don't currently use Windows at all, so you're mostly on your own on that platform. If you require support, please run aprsc on Linux. I don't think anyone uses aprsc on Windows currently, and because there are enough APRS-IS servers already available, I don't see why it would be necessary to do so.

**Comment by tsk7mde** [comment]
Her is the Output:

thomas.schaefer@RAMPAGE-IV-E /opt/aprsc/sbin
$ gdb -nw aprsc.exe
GNU gdb (GDB) (Cygwin 7.10.1-1) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-pc-cygwin".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from aprsc.exe...done.
(gdb) run
Starting program: /opt/aprsc/sbin/aprsc.exe
[New Thread 6412.0xeb4]
[New Thread 6412.0x2200]
[New Thread 6412.0x5aa0]
[New Thread 6412.0x28d4]
[New Thread 6412.0x36a0]
2017/12/04 00:00:38.677001 aprsc[6412:20018020] WARNING: Configuration: setrlimit(RLIMIT_NOFILE) failed: Too many open files
2017/12/04 00:00:38.677036 aprsc[6412:20018020] WARNING: Configuration could not raise FileLimit (not running as root), it is now 3200
[New Thread 6412.0x66d8]
[New Thread 6412.0x5a90]
[New Thread 6412.0x718]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 6412.0x718]
0x6119fcd3 in __chkstk_ms () from /opt/aprsc/sbin/cygwin1.dll
(gdb) continue
Continuing.

Program received signal SIGTRAP, Trace/breakpoint trap.
0x773e2ca3 in KERNELBASE!DebugBreak () from /cygdrive/c/WINDOWS/System32/KERNELBASE.dll
(gdb) continue
Continuing.
[New Thread 6412.0x5d4c]
      0 [unknown (0x5D4C)] aprsc 6412 cygwin_exception::open_stackdumpfile: Dumping stack trace to aprsc.exe.stackdump
[New Thread 6412.0x2988]
[New Thread 6412.0x42e4]
[New Thread 6412.0x6644]
[New Thread 6412.0xacc]
[New Thread 6412.0xdf0]
[New Thread 6412.0x4d28]
[New Thread 6412.0x4c3c]
[Thread 6412.0x5d4c exited with code 0]
[Thread 6412.0x28d4 exited with code 35584]
[Thread 6412.0x66d8 exited with code 35584]
[Thread 6412.0x5aa0 exited with code 35584]
[Thread 6412.0x5a90 exited with code 35584]
[Thread 6412.0x42e4 exited with code 35584]
[Thread 6412.0x36a0 exited with code 35584]
[Thread 6412.0x2988 exited with code 35584]
[Thread 6412.0x6644 exited with code 35584]
[Thread 6412.0xdf0 exited with code 35584]
[Thread 6412.0x2200 exited with code 35584]
[Thread 6412.0xacc exited with code 35584]
[Thread 6412.0x4d28 exited with code 35584]
[Thread 6412.0x718 exited with code 35584]
[Inferior 1 (process 6412) exited with code 0105400]
(gdb) continue
The program is not being run.

**Comment by tsk7mde** [comment]
[LOG_CORE.zip](https://github.com/hessu/aprsc/files/1525306/LOG_CORE.zip)

**Comment by hessu** [comment]
Hi, unfortunately I'm currently not able to assist you or support aprsc on the Windows platform, as described in the previous comment. If you are able to resolve the issue, please file a pull request with the fix.

Sorry!
