### ISSUE TITLE
No user-specified filters on this port

### ISSUE THREAD

**Issue by iddq** [hessu/aprsc#47]
Hello,
Sorry, what does the message "No user-specified filters on this port" mean?
Filters are not allowed?
What is the reason to disabling it?

**Comment by hessu** [comment]
Ports are configured as either ports which support filters, or full-feed ports which do not support filters. Full feed ports do not need to run any filter processing, which makes them marginally faster.

Mostly it's a traditional / compatibility thing with javaprssrvr and the way servers have been set up before.

Use a filtered port if you wish to set up a filter.

**Comment by iddq** [comment]
thanks for the answer.
do you know why javaprs servers don't accept filter t/m?
