### ISSUE TITLE
Invalid callsign in path

### ISSUE THREAD

**Issue by srcejon** [hessu/aprsc#53]
Direwolf generates a packet of the form:

[rx>ig] AISAT-1>CQ,,,qAO,M7RCE::CQ-0     :From  AMSAT INDIA & Exseed Space |3179768|38|36|1070{482

Which results in invalid callsign in path, and the packet being dropped. Is this a direwolf or aprsc problem?

**Comment by hessu** [comment]
That is an invalid path, there are empty callsigns in the path. It's a direwolf problem.

**Comment by wb2osz** [comment]
The AISAT software was written by someone who did not understand the APRS protocol. The satellite was obviously launched without testing the APRS software first to see if it was actually compatible with the rest of the world. It has multiple problems.

Numerous software developers and countless IGate operators should not be expected to kludge the entire worldwide APRS-IS network to accommodate one faulty implementation of a simple protocol that has been around for decades. That would only encourage others to be careless and not do any testing.

Some of the discussion can be found here:

http://lists.tapr.org/pipermail/aprssig_lists.tapr.org/2019-April/047964.html
http://lists.tapr.org/pipermail/aprssig_lists.tapr.org/2019-April/047994.html
http://lists.tapr.org/pipermail/aprssig_lists.tapr.org/2019-April/047995.html
http://lists.tapr.org/pipermail/aprssig_lists.tapr.org/2019-April/047996.html
http://lists.tapr.org/pipermail/aprssig_lists.tapr.org/2019-April/047997.html

**Comment by hessu** [comment]
Oh right, it's this buggy bird we're talking about, I had forgotten about it. I agree with @wb2osz - the satellite software itself is buggy and they should simply fix it and upload a new firmware (firmware update should be the only single "must have" feature that they should have in the first place).
