### ISSUE TITLE
New URL of aprsc discussion group

### ISSUE THREAD

**Issue by TahomaSoft** [hessu/aprsc#59]
The discussion group for this software, as provided in the documentation (https://groups.google.com/forum/#!forum/aprsc) doesn't seem to exist.  Is there an updated URL for it?

Thanks!!

**Comment by snip** [comment]
Group does exist.
But maybe recent changes on Google group setting moved it to private/hidden groupe.
@hessu ?

**Comment by hessu** [comment]
Right, the link still works (redirects to the current new URL), but the recent changes made the group contents only visible to members. Anyone could still request to join.
Updated the settings to allow anyone to read. I'll update the URLs later although the old ones still work for the time being.

**Comment by TahomaSoft** [comment]
Thank you!  That works much better now. Before it appeared to no longer exist. Now the default is (when not signed into google), you can see the postings, but can't see where to request to join.  Once I log on to my google account, then I can see the request.

**Comment by TahomaSoft** [comment]
Just submitted a request to join.  Thanks again!
