### ISSUE TITLE
APRS-IS Packets Being Denied

### ISSUE THREAD

**Issue by na7q** [hessu/aprsc#61]
I'd like to bring up the issue once again. I'm unsure if it has been resolved in future updates. Though I don't believe it has, as I still see the same issues of packets not being igated when they should be. This has been very problematic and frustrating.

https://github.com/hessu/aprsc/issues/48

I was setting up some new stations and once again, had the issue that neither would igate without being "rejected" by the server. They happened to end up on the same servers but in 2 different locations. The end result, lost packets that can be critical in a time of need.

**Comment by hessu** [comment]
Let's continue the discussion on the existing ticket #48 if you like. Please do not open duplicate tickets for the same question. Thanks!
