### ISSUE TITLE
Updated GPG Key Install on Ubuntu and Debian

### ISSUE THREAD

**Issue by TahomaSoft** [hessu/aprsc#77]
In Debian and Ubuntu, apt-key is being deprecated and planned EOL in Ubuntu is with Version 22.04 LTS.

So step (2) below (from he.fi/aprsc/INSTALLING.HTML) currently gives a warning and at some point will fail:

1) gpg --keyserver keyserver.ubuntu.com --recv C51AA22389B5B74C3896EF3CA72A581E657A2B8D
2) gpg --export C51AA22389B5B74C3896EF3CA72A581E657A2B8D | sudo apt-key add -

Instead, step (2) should be something like:
2) sudo gpg --export C51AA22389B5B74C3896EF3CA72A581E657A2B8D > /etc/apt/trusted.gpg.d/aprsc.key.gpg

**Comment by daskalovst** [comment]
Err:7 http://aprsc-dist.he.fi/aprsc/apt DISTRIBUTION Release
  404  Not Found [IP: 85.188.1.22 80]
Reading package lists... Done
E: The repository 'http://aprsc-dist.he.fi/aprsc/apt DISTRIBUTION Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by hessu** [comment]
@daskalovst Please follow the installation instructions at https://github.com/hessu/aprsc/blob/main/doc/INSTALLING.md - please read them a bit more carefully, there are a few words about the DISTRIBUTION keyword in there. :)

**Comment by hessu** [comment]
https://github.com/hessu/aprsc/pull/86 should finally fix this.

**Comment by TahomaSoft** [comment]
Thank you Hessu! Will take a look.
